[build]
  command = "NODE_OPTIONS='--max-old-space-size=6144' pnpm run build"
  publish = "build/client"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm run dev"
  port = 5173
  targetPort = 5173
  autoLaunch = false
